name: Push Default and Deploy - Reusable Workflow

on: 
  push:
     branches:
       - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
   group: push-default-and-deploy-with-rw-${{ github.ref }}
   cancel-in-progress: false

jobs:
   build-and-test:
     runs-on: ubuntu-latest

     steps:
       - name: Start Build Indicator
         env:
            LIFX_BULB_LOCATION: ${{ vars.LIFX_BULB_LOCATION }}
            LIFX_TOKEN: ${{ secrets.LIFX_TOKEN }}
         run: |
           curl -X POST "https://api.lifx.com/v1/lights/$LIFX_BULB_LOCATION/effects/breathe" \
           -H "Authorization: Bearer $LIFX_TOKEN" \
           -d 'color=blue' \
           -d 'period=4' \
           -d 'cycles=450' \
           -d 'from_color=pink'
       - name: Build and Publish .NET Core App
         uses: devopselvis/build-test-net-core-app-custom-action@main
         with:
            dotnet-version: "8.0.x"
            project-path: "${{ github.workspace }}/src/my-web-app/my-web-app.csproj"
            output-path: "mywebapp"
  
   deploy-to-dev:
      needs: build-and-test
      uses: xxdhuehue/pipeline/.github/workflows/reusable.yml@main
      with:
        environment-name: "DEV"
        environment-url: "https://${{ vars.WEB_APP_NAME }}-dev.azurewebsites.net/"
        artifact-name: "myapp"
        web-app-name: ${{ vars.WEB_APP_NAME }}
        slot-name: "dev"
      secrets: inherit
  
